version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizzeria
    volumes:
      - ./src/resources/migrations:/app/migrations

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizzeria
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: